import type { CategoryTag, SpecialtyTag } from "./types";

export interface StaticCuratedCafe {
  id: string;
  curatedName: string;
  searchQuery: string;
  cityArea: string;
  categoryTags: CategoryTag[];
  specialtyTags: SpecialtyTag[];
  visitedByMe: boolean;
  matchaAvailable: boolean;
  coffeeAvailable: boolean;
  notes?: string;
}

export const CURATED_CAFES: StaticCuratedCafe[] = [
  {
    id: "marcels-defence-colony",
    curatedName: "Marcels Defence Colony",
    searchQuery: "Marcels Defence Colony Delhi cafe",
    cityArea: "Defence Colony",
    categoryTags: ["Date Spots", "South Delhi Staples", "Weekend Coffee Crawl", "Visited By Me"],
    specialtyTags: ["flat white", "pastries", "aesthetic", "date spot"],
    visitedByMe: true,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "rush-gk-matcha",
    curatedName: "Rush GK",
    searchQuery: "Rush cafe Greater Kailash Delhi matcha coffee",
    cityArea: "Greater Kailash",
    categoryTags: ["Matcha Trail", "South Delhi Staples", "Visited By Me"],
    specialtyTags: ["matcha", "specialty coffee", "aesthetic"],
    visitedByMe: true,
    matchaAvailable: true,
    coffeeAvailable: true,
  },
  {
    id: "hinoki-matcha-delhi",
    curatedName: "Hinoki",
    searchQuery: "Hinoki matcha cafe Delhi",
    cityArea: "South Delhi",
    categoryTags: ["Matcha Trail", "New To Try"],
    specialtyTags: ["matcha", "japanese", "aesthetic"],
    visitedByMe: false,
    matchaAvailable: true,
    coffeeAvailable: true,
  },
  {
    id: "espresso-anyday-gurgaon",
    curatedName: "Espresso Anyday",
    searchQuery: "Espresso Anyday Gurgaon cafe",
    cityArea: "Gurgaon",
    categoryTags: ["Gurgaon Coffee Map", "Work Cafés", "Visited By Me"],
    specialtyTags: ["specialty coffee", "work friendly", "flat white"],
    visitedByMe: true,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "1000-coffee-galleria-gurgaon",
    curatedName: "1000 Coffee",
    searchQuery: "1000 Coffee Galleria Gurgaon",
    cityArea: "Gurgaon",
    categoryTags: ["Gurgaon Coffee Map", "Weekend Coffee Crawl", "Visited By Me"],
    specialtyTags: ["specialty coffee", "aesthetic", "cozy"],
    visitedByMe: true,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "nunkun-lodhi-delhi",
    curatedName: "Nunkun",
    searchQuery: "Nunkun cafe Lodhi Colony Delhi",
    cityArea: "Lodhi Colony",
    categoryTags: ["South Delhi Staples", "Work Cafés", "Hidden Gems", "Visited By Me"],
    specialtyTags: ["specialty coffee", "healthy bowls", "work friendly"],
    visitedByMe: true,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "savorworks-gk",
    curatedName: "Savorworks GK — Tiramisu Latte",
    searchQuery: "Savorworks cafe Greater Kailash Delhi",
    cityArea: "Greater Kailash",
    categoryTags: ["South Delhi Staples", "Weekend Coffee Crawl", "Visited By Me"],
    specialtyTags: ["tiramisu latte", "specialty coffee", "aesthetic"],
    visitedByMe: true,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "avaya-green-park",
    curatedName: "Avaya — Vietnamese Coffee & Burnt Caramel",
    searchQuery: "Avaya cafe Green Park Delhi Vietnamese coffee",
    cityArea: "Green Park",
    categoryTags: ["Vietnamese Coffee Trail", "Hidden Gems", "Visited By Me"],
    specialtyTags: ["vietnamese coffee", "burnt caramel", "specialty coffee"],
    visitedByMe: true,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "brims-delhi",
    curatedName: "Brims",
    searchQuery: "Brims cafe Delhi specialty coffee",
    cityArea: "South Delhi",
    categoryTags: ["South Delhi Staples", "Work Cafés", "Visited By Me"],
    specialtyTags: ["specialty coffee", "cozy", "work friendly"],
    visitedByMe: true,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "enjis-gurgaon",
    curatedName: "Enjis — Vietnamese Coffee",
    searchQuery: "Enjis cafe Gurgaon Vietnamese coffee",
    cityArea: "Gurgaon",
    categoryTags: ["Vietnamese Coffee Trail", "Gurgaon Coffee Map", "Visited By Me"],
    specialtyTags: ["vietnamese coffee", "specialty coffee"],
    visitedByMe: true,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "libertario-coffee-delhi",
    curatedName: "Libertario Coffee",
    searchQuery: "Libertario Coffee Delhi",
    cityArea: "South Delhi",
    categoryTags: ["South Delhi Staples", "Work Cafés", "Visited By Me"],
    specialtyTags: ["specialty coffee", "flat white", "work friendly"],
    visitedByMe: true,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "roastery-coffee-house-delhi",
    curatedName: "Roastery Coffee House",
    searchQuery: "Roastery Coffee House Delhi",
    cityArea: "South Delhi",
    categoryTags: ["South Delhi Staples", "Coffee Passport", "New To Try"],
    specialtyTags: ["specialty coffee", "single origin", "filter coffee"],
    visitedByMe: false,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "paris-coffee-house-gk2",
    curatedName: "Paris Coffee House GK 2",
    searchQuery: "Paris Coffee House Greater Kailash 2 Delhi",
    cityArea: "Greater Kailash 2",
    categoryTags: ["Weekend Coffee Crawl", "South Delhi Staples", "New To Try"],
    specialtyTags: ["pastries", "cozy", "aesthetic", "french"],
    visitedByMe: false,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "ek-andaaz-coffee-window",
    curatedName: "Ek Andaaz Coffee Window",
    searchQuery: "Ek Andaaz coffee window South Delhi",
    cityArea: "South Delhi",
    categoryTags: ["Hidden Gems", "New To Try"],
    specialtyTags: ["grab and go", "specialty coffee", "lowkey"],
    visitedByMe: false,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "cortado-coffee-delhi",
    curatedName: "Cortado Coffee",
    searchQuery: "Cortado Coffee Delhi cafe",
    cityArea: "South Delhi",
    categoryTags: ["Vietnamese Coffee Trail", "Hidden Gems", "Visited By Me"],
    specialtyTags: ["vietnamese coffee", "specialty coffee"],
    visitedByMe: true,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "subko-gk-delhi",
    curatedName: "Subko GK",
    searchQuery: "Subko cafe Greater Kailash Delhi specialty coffee",
    cityArea: "Greater Kailash",
    categoryTags: ["Work Cafés", "South Delhi Staples", "Coffee Passport", "New To Try"],
    specialtyTags: ["specialty coffee", "single origin", "work friendly"],
    visitedByMe: false,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "ikigai-defence-colony",
    curatedName: "Ikigai",
    searchQuery: "Ikigai cafe Defence Colony Delhi",
    cityArea: "Defence Colony",
    categoryTags: ["Date Spots", "South Delhi Staples", "New To Try"],
    specialtyTags: ["aesthetic", "cozy", "pastries", "date spot"],
    visitedByMe: false,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "daily-drama-defence-colony",
    curatedName: "Daily Drama",
    searchQuery: "Daily Drama cafe Defence Colony Delhi",
    cityArea: "Defence Colony",
    categoryTags: ["Date Spots", "Weekend Coffee Crawl", "New To Try"],
    specialtyTags: ["aesthetic", "date spot", "brunch"],
    visitedByMe: false,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "usco-shahpur-jat",
    curatedName: "Usco",
    searchQuery: "Usco coffee Shahpur Jat Delhi",
    cityArea: "Shahpur Jat",
    categoryTags: ["Hidden Gems", "New To Try"],
    specialtyTags: ["specialty coffee", "lowkey", "aesthetic"],
    visitedByMe: false,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "akura-coffee-gurgaon",
    curatedName: "Akura Coffee",
    searchQuery: "Akura Coffee Gurgaon",
    cityArea: "Gurgaon",
    categoryTags: ["Gurgaon Coffee Map", "New To Try"],
    specialtyTags: ["specialty coffee", "aesthetic"],
    visitedByMe: false,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "beanly-panchsheel-park",
    curatedName: "Beanly",
    searchQuery: "Beanly cafe Panchsheel Park Delhi",
    cityArea: "Panchsheel Park",
    categoryTags: ["Work Cafés", "South Delhi Staples", "Visited By Me"],
    specialtyTags: ["specialty coffee", "work friendly", "cozy"],
    visitedByMe: true,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "common-time-lodhi",
    curatedName: "Common Time",
    searchQuery: "Common Time cafe Lodhi Delhi",
    cityArea: "Lodhi",
    categoryTags: ["Hidden Gems", "Date Spots", "New To Try"],
    specialtyTags: ["aesthetic", "cozy", "specialty coffee"],
    visitedByMe: false,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "the-suk-delhi",
    curatedName: "The Suk",
    searchQuery: "The Suk cafe Delhi",
    cityArea: "South Delhi",
    categoryTags: ["Date Spots", "New To Try"],
    specialtyTags: ["aesthetic", "date spot", "cozy"],
    visitedByMe: false,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "monique-nfc",
    curatedName: "Monique",
    searchQuery: "Monique cafe New Friends Colony Delhi",
    cityArea: "New Friends Colony",
    categoryTags: ["Date Spots", "South Delhi Staples", "New To Try"],
    specialtyTags: ["pastries", "aesthetic", "cozy", "date spot"],
    visitedByMe: false,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "rose-cafe-eldeco",
    curatedName: "Rose Cafe",
    searchQuery: "Rose Cafe Eldeco Delhi",
    cityArea: "Eldeco",
    categoryTags: ["Date Spots", "Weekend Coffee Crawl", "New To Try"],
    specialtyTags: ["aesthetic", "pastries", "cozy", "date spot"],
    visitedByMe: false,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "good-hood-window-delhi",
    curatedName: "Good Hood Window",
    searchQuery: "Good Hood coffee window Delhi",
    cityArea: "South Delhi",
    categoryTags: ["Hidden Gems", "New To Try"],
    specialtyTags: ["grab and go", "specialty coffee", "lowkey"],
    visitedByMe: false,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "caarabi-coffee-roasters",
    curatedName: "Caarabi Coffee Roasters",
    searchQuery: "Caarabi Coffee Roasters Delhi",
    cityArea: "Delhi",
    categoryTags: ["Work Cafés", "Coffee Passport", "New To Try"],
    specialtyTags: ["specialty coffee", "single origin", "filter coffee"],
    visitedByMe: false,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "seven-seeds-coffee-delhi",
    curatedName: "Seven Seeds Coffee",
    searchQuery: "Seven Seeds Coffee Delhi specialty",
    cityArea: "Delhi",
    categoryTags: ["Work Cafés", "Coffee Passport", "New To Try"],
    specialtyTags: ["specialty coffee", "filter coffee", "single origin", "work friendly"],
    visitedByMe: false,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "firenze-delhi",
    curatedName: "Firenze",
    searchQuery: "Firenze cafe Delhi Italian coffee",
    cityArea: "South Delhi",
    categoryTags: ["Date Spots", "Weekend Coffee Crawl", "Visited By Me"],
    specialtyTags: ["italian", "pastries", "aesthetic", "date spot"],
    visitedByMe: true,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "kokoy-gurgaon",
    curatedName: "Kokoy",
    searchQuery: "Kokoy cafe Gurgaon",
    cityArea: "Gurgaon",
    categoryTags: ["Gurgaon Coffee Map", "New To Try"],
    specialtyTags: ["specialty coffee", "healthy bowls", "aesthetic"],
    visitedByMe: false,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "lofin-lodhi",
    curatedName: "Lofin",
    searchQuery: "Lofin cafe Lodhi Delhi",
    cityArea: "Lodhi",
    categoryTags: ["Hidden Gems", "Date Spots", "New To Try"],
    specialtyTags: ["aesthetic", "cozy", "date spot"],
    visitedByMe: false,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "petes-deli-delhi",
    curatedName: "Pete's Deli",
    searchQuery: "Pete's Deli Delhi cafe",
    cityArea: "South Delhi",
    categoryTags: ["Weekend Coffee Crawl", "South Delhi Staples", "Visited By Me"],
    specialtyTags: ["sandwiches", "pastries", "cozy"],
    visitedByMe: true,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "byterra-hauz-khas",
    curatedName: "Byterra",
    searchQuery: "Byterra cafe Hauz Khas Delhi",
    cityArea: "Hauz Khas",
    categoryTags: ["Work Cafés", "South Delhi Staples", "New To Try"],
    specialtyTags: ["work friendly", "specialty coffee", "cozy"],
    visitedByMe: false,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "nubo-hauz-khas",
    curatedName: "Nubo",
    searchQuery: "Nubo cafe Hauz Khas Delhi rooftop",
    cityArea: "Hauz Khas",
    categoryTags: ["Date Spots", "Weekend Coffee Crawl", "New To Try"],
    specialtyTags: ["aesthetic", "rooftop", "date spot"],
    visitedByMe: false,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "kko-delhi",
    curatedName: "KKO",
    searchQuery: "KKO cafe Delhi specialty coffee",
    cityArea: "South Delhi",
    categoryTags: ["Weekend Coffee Crawl", "New To Try"],
    specialtyTags: ["specialty coffee", "cozy", "aesthetic"],
    visitedByMe: false,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "la-tarte-gk2",
    curatedName: "La Tarte",
    searchQuery: "La Tarte cafe Greater Kailash 2 Delhi",
    cityArea: "Greater Kailash 2",
    categoryTags: ["Date Spots", "Weekend Coffee Crawl", "New To Try"],
    specialtyTags: ["pastries", "aesthetic", "french", "date spot"],
    visitedByMe: false,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "jays-coffee-delhi",
    curatedName: "Jay's Coffee",
    searchQuery: "Jay's Coffee Delhi cafe specialty",
    cityArea: "South Delhi",
    categoryTags: ["Weekend Coffee Crawl", "South Delhi Staples", "New To Try"],
    specialtyTags: ["specialty coffee", "flat white"],
    visitedByMe: false,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "pourover-coffee-santushti",
    curatedName: "Pourover Coffee",
    searchQuery: "Pourover coffee Santushti Delhi",
    cityArea: "Santushti",
    categoryTags: ["Work Cafés", "Coffee Passport", "New To Try"],
    specialtyTags: ["filter coffee", "pour over", "specialty coffee", "work friendly"],
    visitedByMe: false,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "tan-coffee-delhi",
    curatedName: "Tan Coffee",
    searchQuery: "Tan Coffee Delhi specialty",
    cityArea: "South Delhi",
    categoryTags: ["Work Cafés", "Hidden Gems", "New To Try"],
    specialtyTags: ["specialty coffee", "lowkey", "work friendly"],
    visitedByMe: false,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "savage-sandwiches-hauz-khas",
    curatedName: "Savage Sandwiches",
    searchQuery: "Savage Sandwiches Hauz Khas Delhi cafe",
    cityArea: "Hauz Khas",
    categoryTags: ["Weekend Coffee Crawl", "South Delhi Staples", "New To Try"],
    specialtyTags: ["sandwiches", "specialty coffee", "cozy"],
    visitedByMe: false,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "tutto-gusto-coffee",
    curatedName: "Tutto Gusto Coffee",
    searchQuery: "Tutto Gusto Coffee South Delhi cafe",
    cityArea: "South Delhi",
    categoryTags: ["South Delhi Staples", "New To Try"],
    specialtyTags: ["italian", "specialty coffee", "aesthetic"],
    visitedByMe: false,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "doki-doki-saket",
    curatedName: "Doki Doki",
    searchQuery: "Doki Doki cafe Saket Delhi matcha",
    cityArea: "Saket",
    categoryTags: ["Matcha Trail", "New To Try"],
    specialtyTags: ["matcha", "japanese", "aesthetic"],
    visitedByMe: false,
    matchaAvailable: true,
    coffeeAvailable: true,
  },
  {
    id: "ate-safdarjung",
    curatedName: "ATE",
    searchQuery: "ATE cafe Safdarjung Delhi specialty coffee",
    cityArea: "Safdarjung",
    categoryTags: ["Hidden Gems", "New To Try"],
    specialtyTags: ["specialty coffee", "grab and go", "lowkey"],
    visitedByMe: false,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "shift-coffee-boulevard",
    curatedName: "Shift Coffee Boulevard",
    searchQuery: "Shift Coffee Boulevard Delhi",
    cityArea: "Delhi",
    categoryTags: ["Work Cafés", "New To Try"],
    specialtyTags: ["specialty coffee", "work friendly", "aesthetic"],
    visitedByMe: false,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "cala-panchsheel",
    curatedName: "Cala",
    searchQuery: "Cala cafe Panchsheel Park Delhi",
    cityArea: "Panchsheel Park",
    categoryTags: ["Weekend Coffee Crawl", "Date Spots", "New To Try"],
    specialtyTags: ["aesthetic", "cozy", "pastries", "date spot"],
    visitedByMe: false,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "louve-delhi",
    curatedName: "Louve",
    searchQuery: "Louve cafe Delhi French",
    cityArea: "South Delhi",
    categoryTags: ["Date Spots", "New To Try"],
    specialtyTags: ["aesthetic", "french", "date spot", "pastries"],
    visitedByMe: false,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "chai-and-co-gurgaon",
    curatedName: "Chai and Co — Matcha",
    searchQuery: "Chai and Co Gurgaon matcha cafe",
    cityArea: "Gurgaon",
    categoryTags: ["Matcha Trail", "Gurgaon Coffee Map", "New To Try"],
    specialtyTags: ["matcha", "specialty coffee"],
    visitedByMe: false,
    matchaAvailable: true,
    coffeeAvailable: true,
  },
  {
    id: "vikoli-gurgaon",
    curatedName: "Vikoli",
    searchQuery: "Vikoli cafe Gurgaon specialty coffee",
    cityArea: "Gurgaon",
    categoryTags: ["Gurgaon Coffee Map", "New To Try"],
    specialtyTags: ["specialty coffee", "aesthetic"],
    visitedByMe: false,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "savorworks-gurgaon",
    curatedName: "Savorworks Gurgaon",
    searchQuery: "Savorworks cafe Gurgaon specialty coffee",
    cityArea: "Gurgaon",
    categoryTags: ["Gurgaon Coffee Map", "Work Cafés", "Visited By Me"],
    specialtyTags: ["tiramisu latte", "specialty coffee", "work friendly"],
    visitedByMe: true,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "gramstreet-gurgaon",
    curatedName: "Gramstreet",
    searchQuery: "Gramstreet cafe Gurgaon specialty coffee",
    cityArea: "Gurgaon",
    categoryTags: ["Gurgaon Coffee Map", "Weekend Coffee Crawl", "Visited By Me"],
    specialtyTags: ["specialty coffee", "aesthetic", "work friendly"],
    visitedByMe: true,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "jays-coffee-chattarpur",
    curatedName: "Jay's Coffee Chattarpur",
    searchQuery: "Jay's Coffee Chattarpur Delhi cafe",
    cityArea: "Chattarpur",
    categoryTags: ["Weekend Coffee Crawl", "New To Try"],
    specialtyTags: ["specialty coffee", "cozy"],
    visitedByMe: false,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "genre-defence-colony",
    curatedName: "Genre",
    searchQuery: "Genre cafe Defence Colony Delhi",
    cityArea: "Defence Colony",
    categoryTags: ["Date Spots", "South Delhi Staples", "Weekend Coffee Crawl", "Visited By Me"],
    specialtyTags: ["aesthetic", "specialty coffee", "cozy", "date spot"],
    visitedByMe: true,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "95-delhi",
    curatedName: "95",
    searchQuery: "95 cafe Delhi specialty coffee",
    cityArea: "South Delhi",
    categoryTags: ["South Delhi Staples", "Work Cafés", "Visited By Me"],
    specialtyTags: ["specialty coffee", "aesthetic", "work friendly"],
    visitedByMe: true,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "coffee-under-palms-vasant-kunj",
    curatedName: "Coffee Under Palms",
    searchQuery: "Coffee Under Palms Vasant Kunj Delhi cafe",
    cityArea: "Vasant Kunj",
    categoryTags: ["South Delhi Staples", "Weekend Coffee Crawl", "New To Try"],
    specialtyTags: ["aesthetic", "cozy", "specialty coffee"],
    visitedByMe: false,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
  {
    id: "thamel-gurgaon",
    curatedName: "Thamel",
    searchQuery: "Thamel cafe Gurgaon coffee",
    cityArea: "Gurgaon",
    categoryTags: ["Gurgaon Coffee Map", "Hidden Gems", "New To Try"],
    specialtyTags: ["specialty coffee", "aesthetic", "cozy"],
    visitedByMe: false,
    matchaAvailable: false,
    coffeeAvailable: true,
  },
];

export const CURATED_TRAILS = [
  {
    id: "matcha",
    name: "Matcha Trail",
    emoji: "🍵",
    description: "Delhi's finest matcha destinations",
    tag: "Matcha Trail" as CategoryTag,
  },
  {
    id: "vietnamese",
    name: "Vietnamese Coffee",
    emoji: "☕",
    description: "Ca phe sữa đá, South Delhi style",
    tag: "Vietnamese Coffee Trail" as CategoryTag,
  },
  {
    id: "hidden-gems",
    name: "Hidden Gems",
    emoji: "💎",
    description: "Under the radar, worth the detour",
    tag: "Hidden Gems" as CategoryTag,
  },
  {
    id: "date-spots",
    name: "Date Spots",
    emoji: "🌹",
    description: "Atmosphere worth sharing",
    tag: "Date Spots" as CategoryTag,
  },
  {
    id: "work-cafes",
    name: "Work Cafés",
    emoji: "💻",
    description: "Wifi, good coffee, no judgment",
    tag: "Work Cafés" as CategoryTag,
  },
  {
    id: "gurgaon",
    name: "Gurgaon Map",
    emoji: "🗺️",
    description: "The new Gurugram coffee scene",
    tag: "Gurgaon Coffee Map" as CategoryTag,
  },
  {
    id: "weekend-crawl",
    name: "Weekend Crawl",
    emoji: "🚶",
    description: "Saturday morning, no agenda",
    tag: "Weekend Coffee Crawl" as CategoryTag,
  },
  {
    id: "visited",
    name: "My Passport",
    emoji: "📔",
    description: "Places already stamped",
    tag: "Visited By Me" as CategoryTag,
  },
  {
    id: "new-to-try",
    name: "New To Try",
    emoji: "✨",
    description: "On the list, not yet stamped",
    tag: "New To Try" as CategoryTag,
  },
];

export const VISITED_IDS = new Set(
  CURATED_CAFES.filter((c) => c.visitedByMe).map((c) => c.id)
);
