import type { Cafe } from "./types";

// Minimal fallback — only used when both Supabase and Google Places are unavailable.
// These are real cafés from the curated list.
export const MOCK_CAFES: Cafe[] = [
  {
    id: "mock-marcels",
    name: "Marcels",
    address: "Defence Colony, South Delhi",
    rating: 4.6,
    reviewCount: 820,
    photoNames: [],
    photoUrls: [], // no real photo — UI shows "No Photo Available" state
    hoursText: "9:00 AM – 10:00 PM",
    weekdayHours: [],
    isOpen: true,
    priceLevel: 3,
    matchScore: 92,
    matchReason: "A Defence Colony staple known for its flat whites and pastry selection.",
    vibe: "Aesthetic & Curated",
    specialties: ["Flat White", "Pastries"],
    lat: 28.5726, lng: 77.2270,
    types: [],
    isCurated: true,
    curatedName: "Marcels Defence Colony",
    cityArea: "Defence Colony",
    categoryTags: ["Date Spots", "South Delhi Staples", "Weekend Coffee Crawl"],
    specialtyTags: ["flat white", "pastries", "aesthetic", "date spot"],
    visitedByMe: true, matchReasons: [],
  },
  {
    id: "mock-nunkun",
    name: "Nunkun",
    address: "Lodhi Colony, South Delhi",
    rating: 4.7,
    reviewCount: 650,
    photoNames: [],
    photoUrls: [],
    hoursText: "8:00 AM – 9:00 PM",
    weekdayHours: [],
    isOpen: true,
    priceLevel: 2,
    matchScore: 90,
    matchReason: "Lodhi Colony's most focused specialty café. Serious coffee, quiet space.",
    vibe: "Quiet & Focused",
    specialties: ["Specialty Coffee", "Healthy Bowls"],
    lat: 28.5918, lng: 77.2273,
    types: [],
    isCurated: true,
    curatedName: "Nunkun Lodhi Delhi",
    cityArea: "Lodhi Colony",
    categoryTags: ["South Delhi Staples", "Work Cafés", "Hidden Gems"],
    specialtyTags: ["specialty coffee", "healthy bowls", "work friendly"],
    visitedByMe: true, matchReasons: [],
  },
  {
    id: "mock-subko",
    name: "Subko",
    address: "Greater Kailash, South Delhi",
    rating: 4.5,
    reviewCount: 1200,
    photoNames: [],
    photoUrls: [],
    hoursText: "9:00 AM – 9:00 PM",
    weekdayHours: [],
    isOpen: true,
    priceLevel: 3,
    matchScore: 88,
    matchReason: "Single-origin specialists with a focus on Indian coffee. GK's finest.",
    vibe: "Specialty & Craft",
    specialties: ["Single Origin", "Filter Coffee"],
    lat: 28.5376, lng: 77.2340,
    types: [],
    isCurated: true,
    curatedName: "Subko GK Delhi",
    cityArea: "Greater Kailash",
    categoryTags: ["Work Cafés", "South Delhi Staples", "Coffee Passport"],
    specialtyTags: ["specialty coffee", "single origin", "work friendly"],
    visitedByMe: false, matchReasons: [],
  },
];
